// TEMPORARY DATA

export let role = "admin";

export const itData = [
  {
    id: 1,
    itId: "1234567890",
    name: "Johan Grobbelaar",
    email: "johan@africlangroup.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    groups: ["Accounts", "Opperations", "Stores"],
    companies: ["Advance", "Cancam", "Copperzone", "Headland"],
    sex: "male",
    birthday: "1990-01-01",
  },
  {
    id: 2,
    itID: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    groups: ["Workshops", "Administration", "Other"],
    companies: ["Jumaras", "Nexgistix", "Vectura", "Wavelengths"],
    address: "123 Main St, Anytown, USA",
    sex: "male",
    birthday: "1990-01-01",
  },
  {
    id: 3,
    itID: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    groups: ["Biology"],
    companies: ["Africlan JHB", "Africlan ZM"],
    address: "123 Main St, Anytown, USA",
    sex: "male",
    birthday: "1990-01-01",
  },
  {
    id: 4,
    itID: "1234567890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    groups: ["History"],
    companies: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
    sex: "male",
    birthday: "1990-01-01",
  },
  {
    id: 5,
    itID: "1234567890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    groups: ["Music", "History"],
    companies: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
    sex: "male",
    birthday: "1990-01-01",
  },
  {
    id: 6,
    itID: "1234567890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    groups: ["Physics"],
    companies: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
    sex: "male",
    birthday: "1990-01-01",
  },
  {
    id: 7,
    itID: "1234567890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    groups: ["English", "Spanish"],
    companies: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
    sex: "male",
    birthday: "1990-01-01",
  },
  {
    id: 8,
    itID: "1234567890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    groups: ["Math", "Geometry"],
    companies: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
    sex: "male",
    birthday: "1990-01-01",
  },
  {
    id: 9,
    itID: "1234567890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    groups: ["Literature", "English"],
    companies: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
    sex: "male",
    birthday: "1990-01-01",
  },
  {
    id: 10,
    itID: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    groups: ["Biology"],
    companies: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
    sex: "male",
    birthday: "1990-01-01",
  },
];

export const staffData = [
  {
    id: 1,
    staffId: "1234567890",
    name: "John Doe",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    company: 5,
    group: "1B",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    staffId: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    company: 5,
    group: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    staffId: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    company: 5,
    group: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    staffId: "1234567890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    company: 5,
    group: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    staffId: "1234567890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    company: 5,
    group: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    staffId: "1234567890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    company: 5,
    group: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    staffId: "1234567890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    company: 5,
    group: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    staffId: "1234567890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    company: 5,
    group: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    staffId: "1234567890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    company: 5,
    group: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    staffId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    company: 5,
    group: "5A",
    address: "123 Main St, Anytown, USA",
  },
];

export const hocData = [
  {
    id: 1,
    name: "John Doe",
    photo: "/Advance.jpg",
    staff: ["Sarah Brewer"],
    email: "john@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
    company: "Advance",
  },
  {
    id: 2,
    name: "Jane Doe",
    photo: "/Cancam.jpg",
    staff: ["Cecilia Bradley"],
    email: "jane@doe.com",
    phone: "1234567890",
    company: "Cancam",
  },
  {
    id: 3,
    name: "Mike Geller",
    photo: "/Copperzone.jpg",
    staff: ["Fanny Caldwell"],
    email: "mike@geller.com",
    phone: "1234567890",
    company: "Copperzone",
  },
  {
    id: 4,
    name: "Jay French",
    photo: "/Headland.jpg",
    staff: ["Mollie Fitzgerald", "Ian Bryant"],
    email: "mike@geller.com",
    phone: "1234567890",
    company: "Headland",
  },
  {
    id: 5,
    name: "Jane Smith",
    photo: "/Jumaras.jpg",
    staff: ["Mable Harvey"],
    email: "mike@geller.com",
    phone: "1234567890",
    company: "Jumaras",
  },
  {
    id: 6,
    name: "Anna Santiago",
    photo: "/Nexgistix.jpg",
    staff: ["Joel Lambert"],
    email: "mike@geller.com",
    phone: "1234567890",
    company: "Nexgistix",
  },
  {
    id: 7,
    name: "Allen Black",
    photo: "/Vectura.jpg",
    staff: ["Carrie Tucker", "Lilly Underwood"],
    email: "mike@geller.com",
    phone: "1234567890",
    company: "Vectura",
  },
  {
    id: 8,
    name: "Ophelia Castro",
    photo: "/Wavelengths.png",
    staff: ["Alexander Blair"],
    email: "mike@geller.com",
    phone: "1234567890",
    company: "Wavelengths",
  },
  {
    id: 9,
    name: "Derek Briggs",
    photo: "/AfriclanJHB.jpg",
    staff: ["Susan Webster", "Maude Stone"],
    email: "mike@geller.com",
    phone: "1234567890",
    company: "Africlan JHB",
  },
  {
    id: 10,
    name: "John Glover",
    photo: "/AfriclanZM.jpg",
    staff: ["Stella Scott"],
    email: "mike@geller.com",
    phone: "1234567890",
    company: "Africlan ZM",
  },
  {
    id: 11,
    name: "John Glover",
    photo: "/Venditime.jpg",
    staff: ["Stella Scott"],
    email: "mike@geller.com",
    phone: "1234567890",
    company: "Venditime",
  },
];

export const groupsData = [
  {
    id: 1,
    name: "Accounts",
    staff: ["John Doe", "Jane Smith", "Mike Geller"],
  },
  {
    id: 2,
    name: "Opperations",
    staff: ["John Doe", "Jane Smith", "Mike Geller"],
  },
  {
    id: 3,
    name: "Stores",
    staff: ["John Doe", "Jane Smith", "Mike Geller"],
  },
  {
    id: 4,
    name: "Workshops",
    staff: ["John Doe", "Jane Smith", "Mike Geller"],
  },
  {
    id: 5,
    name: "Administration",
    staff: ["John Doe", "Jane Smith", "Mike Geller"],

  },
  {
    id: 6,
    name: "Other",
    staff: ["John Doe", "Jane Smith", "Mike Geller"],
  },
];

export const companiesData = [
  {
    id: 1,
    name: "Advance",
    photo: "/Advance.jpg",
    hoc: "John Doe",
    staff: ["John Doe", "Jane Smith", "Mike Geller"],
    groups: ["Accounts", "Opperations", "Stores"],
  },
  {
    id: 2,
    name: "Cancam",
    photo: "/Cancam.jpg",
    hoc: "John Doe",
    staff: ["John Doe", "Jane Smith", "Mike Geller"],
    groups: ["Accounts", "Opperations", "Stores"],
  },
  {
    id: 3,
    name: "Copperzone",
    photo: "/Copperzone.jpg",
    hoc: "John Doe",
    staff: ["John Doe", "Jane Smith", "Mike Geller"],
    groups: ["Accounts", "Opperations", "Stores"],
  },
  {
    id: 4,
    name: "Headland",
    photo: "/Headland.jpg",
    hoc: "John Doe",
    staff: ["John Doe", "Jane Smith", "Mike Geller"],
    groups: ["Accounts", "Opperations", "Stores"],
  },
  {
    id: 5,
    name: "Jumaras",
    photo: "/Jumaras.jpg",
    hoc: "John Doe",
    staff: ["John Doe", "Jane Smith", "Mike Geller"],
    groups: ["Accounts", "Opperations", "Stores"],
  },
  {
    id: 5,
    name: "Nexgistix",
    photo: "/Nexgistix.jpg",
    hoc: "John Doe",
    staff: ["John Doe", "Jane Smith", "Mike Geller"],
    groups: ["Accounts", "Opperations", "Stores"],
  },
  {
    id: 7,
    name: "Vectura",
    photo: "/Vectura.jpg",
    hoc: "John Doe",
    staff: ["John Doe", "Jane Smith", "Mike Geller"],
    groups: ["Accounts", "Opperations", "Stores"],
  },
  {
    id: 8,
    name: "Wavelengths",
    hoc: "John Doe",
    photo: "/Wavelengths.png",
    staff: ["John Doe", "Jane Smith", "Mike Geller"],
    groups: ["Accounts", "Opperations", "Stores"],
  },
  {
    id: 9,
    name: "Africlan JHB",
    hoc: "John Doe",
    photo: "/AfriclanJHB.jpg",
    staff: ["John Doe", "Jane Smith", "Mike Geller"],
    groups: ["Accounts", "Opperations", "Stores"],
  },
  {
    id: 10,
    name: "Africlan ZM",
    photo: "/AfriclanZM.jpg",
    hoc: "John Doe",
    staff: ["John Doe", "Jane Smith", "Mike Geller"],
    groups: ["Accounts", "Opperations", "Stores"],
  },
  {
    id: 10,
    name: "Venditime",
    photo: "/Venditime.jpg",
    hoc: "John Doe",
    staff: ["John Doe", "Jane Smith", "Mike Geller"],
    groups: ["Accounts", "Opperations", "Stores"],
  },
];

export const ticketsData = [
  {
    id: 1,
    subject: "Math",
    group: "Accounts",
    company: "Advance",
    staff_member: "Tommy Wise",
    assigned_to: "John Doe",
    description: "Need help with math homework",
    status: "Open",
    attachments: [
      {
        id: 1,
        name: "math_homework.pdf",
        url: "https://example.com/math_homework.pdf",
      },
    ],
    createdAt: "2025-01-01",
    updatedAt: "2025-01-01",
    messages: [
      {
        id: 1,
        sender: "Tommy Wise",
        content: "I need help with my math homework",
        createdAt: "2025-01-01",
      },
    ],
  },
  {
    id: 2,
    subject: "Math",
    group: "Accounts",
    company: "Advance",
    staff_member: "Tommy Wise",
    assigned_to: "John Doe",
    description: "Need help with math homework",
    status: "Open",
    attachments: [
      {
        id: 1,
        name: "math_homework.pdf",
        url: "https://example.com/math_homework.pdf",
      },
    ],
    createdAt: "2025-01-01",
    updatedAt: "2025-01-01",
    messages: [
      {
        id: 1,
        sender: "Tommy Wise",
        content: "I need help with my math homework",
        createdAt: "2025-01-01",
      },
    ],
  },
  {
    id: 3,
    subject: "Math",
    group: "Accounts",
    company: "Advance",
    staff_member: "Tommy Wise",
    assigned_to: "John Doe",
    description: "Need help with math homework",
    status: "Open",
    attachments: [
      {
        id: 1,
        name: "math_homework.pdf",
        url: "https://example.com/math_homework.pdf",
      },
    ],
    createdAt: "2025-01-01",
    updatedAt: "2025-01-01",
    messages: [
      {
        id: 1,
        sender: "Tommy Wise",
        content: "I need help with my math homework",
        createdAt: "2025-01-01",
      },
    ],
  },
];
export const messagesData = [
  {
    id: 1,
    subject: "Math",
    group: "1A",
    teacher: "Martha Morris",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    group: "2A",
    teacher: "Randall Garcia",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    group: "3A",
    teacher: "Myrtie Scott",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    group: "1B",
    teacher: "Alvin Swanson",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    group: "4A",
    teacher: "Mabelle Wallace",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    group: "5A",
    teacher: "Dale Thompson",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    group: "6A",
    teacher: "Allie Conner",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    group: "6B",
    teacher: "Hunter Fuller",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    group: "7A",
    teacher: "Lois Lindsey",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    group: "8A",
    teacher: "Vera Soto",
    date: "2025-01-01",
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    group: "1A",
    date: "2025-08-10",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    group: "2A",
    date: "2025-08-10",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    group: "3A",
    date: "2025-08-10",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    group: "4A",
    date: "2025-08-10",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    group: "5A",
    date: "2025-08-10",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    group: "1B",
    date: "2025-08-10",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    group: "2B",
    date: "2025-08-10",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    group: "3B",
    date: "2025-08-10",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    group: "4B",
    date: "2025-08-10",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    group: "5B",
    date: "2025-10-08",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    group: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    group: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    group: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    group: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    group: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    group: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    group: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    group: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    group: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Math Test",
    group: "1C",
    date: "2025-01-01",
  },
];


// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 7, 10, 8, 0),
    end: new Date(2025, 7, 10, 8, 45), // Changed from 9:00 to keep duration consistent
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 7, 10, 9, 0),
    end: new Date(2025, 7, 10, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 7, 10, 10, 0),
    end: new Date(2025, 7, 10, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 7, 10, 11, 0),
    end: new Date(2025, 7, 10, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 7, 10, 13, 0),
    end: new Date(2025, 7, 10, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 7, 10, 14, 0),
    end: new Date(2025, 7, 10, 14, 45),
  },
];